[package]
name = "unshufflevideo"
version = "0.1.0"
authors = ["Axelle Piot <axellepiot@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
